project:
  type: website
  render:
    - index.qmd
    - c01-color.qmd
    - c02-morphology1.qmd
    - c03-morphology2.qmd
    - c04-morphology3.qmd

website:
  margin-header: |
    ![](/img/slab.png)
  navbar:
    logo: "sfasu.png"
    right:
      - href: index.qmd
        text: Home
      - c01-color.qmd
      - text: Morphology
        menu:
          - c02-morphology1.qmd
          - c03-morphology2.qmd
          - c04-morphology3.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
